# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'NYTimes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NYTimes
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'RxCocoa', '5.0.0'
  pod 'SwiftLint', '0.42.0'
  pod 'Kingfisher', '~> 6.0'

  target 'NYTimesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NYTimesUITests' do
    # Pods for testing
  end

end
